name: Deploy to Lolipop on main

on: 
  push: 
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: LOLIPOP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LOLIPOP_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.LOLIPOP_PORT }} ${{ secrets.LOLIPOP_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to Lolipop
        run: |
          rsync -avz --delete --delay-updates \ 
          -e "ssh -p ${{ secrets.LOLIPOP_PORT }}" \
          out/ \
          ${{ secrets.LOLIPOP_USER }}@${{ secrets.LOLIPOP_HOST }}:${{ secrets.LOLIPOP_TARGET_DIR }}
          